# Generated by Django 3.2.8 on 2021-10-25 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('my_image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='profile/images')),
                ('rating', models.FloatField(blank=True, default=0)),
                ('post_participated', models.ManyToManyField(blank=True, related_name='post_participated_profile', to='main.Post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
