# Generated by Django 3.2.8 on 2021-10-25 12:31

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Offline', '오프라인'), ('Online', '온라인'), ('Delivery', '배달음식')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.TextField(default='')),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.CharField(max_length=50)),
                ('limit', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('link', models.URLField(blank=True, max_length=300, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
