# Generated by Django 3.2.8 on 2021-10-25 13:54

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_post', to='account.profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='post/images'),
        ),
        migrations.AddField(
            model_name='post',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members_post', to='account.Profile'),
        ),
    ]
